apiVersion: v1
data:
  mongo-users: |
    use admin
    db.createUser( {
        user: "admin",
        pwd: "password",
        roles: [ { role: "root", db: "admin" } ]
      });
kind: ConfigMap
metadata:
  name: mongo-users
  namespace: default
